import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import db from '../db/database.js';
import { sendAppointmentNotifications } from '../services/mailer.js';
import { getBerlinDate, getBerlinMinutes } from '../utils/time.js';

const router = Router();
const appointmentLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 8, standardHeaders: true, legacyHeaders: false, message: { message: 'Zu viele Terminanfragen. Bitte versuche es später erneut.' } });
const FALLBACK_HOURS = { 1:['09:00','18:00'], 2:['09:00','18:00'], 3:['09:00','18:00'], 4:['09:00','19:00'], 5:['09:00','19:00'], 6:['09:00','16:00'], 0:null };
const DAY_KEYS = { 1:'hoursMon', 2:'hoursTue', 3:'hoursWed', 4:'hoursThu', 5:'hoursFri', 6:'hoursSat', 0:'hoursSun' };
const STATUSES = ['Neu','Bestätigt','Erledigt','Storniert','Abgelehnt'];
const clean = (value, max=500) => String(value ?? '').trim().slice(0,max);
const validEmail = value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const validDate = value => { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const [y,m,d]=value.split('-').map(Number); const date=new Date(y,m-1,d); return date.getFullYear()===y&&date.getMonth()===m-1&&date.getDate()===d; };
const validTime = value => { if (!/^\d{2}:\d{2}$/.test(value)) return false; const [h,m]=value.split(':').map(Number); return h>=0&&h<24&&m>=0&&m<60; };
function addMinutes(time, minutes) { const [h,m]=time.split(':').map(Number); const total=h*60+m+minutes; return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`; }
function readSettings() { const rows=db.prepare('SELECT key,value FROM settings').all(); return Object.fromEntries(rows.map(row=>[row.key,row.value])); }
function getOpeningHours(day) { const settings=readSettings(); const value=settings[DAY_KEYS[day]]; if (value) { if (/^geschlossen$/i.test(value.trim())) return null; const match=value.replace('–','-').match(/^(\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})$/); if (match) return [match[1],match[2]]; } return FALLBACK_HOURS[day]; }
function slotsForDate(date,durationMinutes=30) { const day=new Date(`${date}T12:00:00`).getDay(); const hours=getOpeningHours(day); if(!hours)return[]; const [sh,sm]=hours[0].split(':').map(Number); const [eh,em]=hours[1].split(':').map(Number); const start=sh*60+sm,end=eh*60+em,result=[]; for(let t=start;t+durationMinutes<=end;t+=30)result.push(`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`); return result; }
function isToday(date) { return date === getBerlinDate(); }
function isBookableDate(date) { return validDate(date)&&date>=getBerlinDate(); }
function getService(serviceId) { return db.prepare('SELECT id,name,duration_minutes FROM services WHERE id=? AND active=1').get(serviceId); }
function getAvailableSlots(date,durationMinutes) { const appointments=db.prepare("SELECT time,end_time AS endTime FROM appointments WHERE date=? AND status IN ('Neu','Bestätigt')").all(date); const currentMinutes=getBerlinMinutes()+1; return slotsForDate(date,durationMinutes).filter(slot=>{if(isToday(date)){const [h,m]=slot.split(':').map(Number);if(h*60+m<currentMinutes)return false;}const end=addMinutes(slot,durationMinutes);return !appointments.some(a=>slot<a.endTime&&end>a.time);}); }
router.get('/settings',(_req,res)=>{ const settings=readSettings(); res.json({settings}); });
router.get('/services',(_req,res)=>{const services=db.prepare('SELECT id,name,category,description,price_from AS priceFrom,duration_minutes AS durationMinutes FROM services WHERE active=1 ORDER BY category,name').all();res.json({services});});
router.get('/availability',(req,res)=>{const date=clean(req.query.date,10),serviceId=Number(req.query.serviceId);if(!isBookableDate(date))return res.status(400).json({message:'Bitte wähle ein gültiges heutiges oder zukünftiges Datum.'});const service=Number.isInteger(serviceId)&&serviceId>0?getService(serviceId):null;if(serviceId&&!service)return res.status(400).json({message:'Dienstleistung wurde nicht gefunden.'});const day=new Date(`${date}T12:00:00`).getDay();res.json({date,openingHours:getOpeningHours(day),slots:getAvailableSlots(date,service?.duration_minutes??30)});});
router.post('/appointments', appointmentLimiter, async(req,res)=>{const body=req.body||{},name=clean(body.name,120),email=clean(body.email,180).toLowerCase(),phone=clean(body.phone,40),date=clean(body.date,10),time=clean(body.time,5),note=clean(body.note,1000),serviceId=Number(body.serviceId);if(name.length<2||phone.length<6||!validEmail(email)||!validDate(date)||!validTime(time)||!Number.isInteger(serviceId))return res.status(400).json({message:'Bitte alle Pflichtfelder korrekt ausfüllen.'});if(!isBookableDate(date))return res.status(400).json({message:'Bitte wähle ein gültiges heutiges oder zukünftiges Datum.'});const service=getService(serviceId);if(!service)return res.status(400).json({message:'Dienstleistung wurde nicht gefunden.'});const availableSlots=getAvailableSlots(date,service.duration_minutes);if(!availableSlots.includes(time))return res.status(400).json({message:'Diese Uhrzeit ist nicht verfügbar.'});const endTime=addMinutes(time,service.duration_minutes);try{const create=db.transaction(()=>{const overlapping=db.prepare("SELECT id FROM appointments WHERE date=? AND status IN ('Neu','Bestätigt') AND time<? AND end_time>? LIMIT 1").get(date,endTime,time);if(overlapping){const error=new Error('SLOT_TAKEN');error.code='SLOT_TAKEN';throw error;}let customer=db.prepare('SELECT id FROM customers WHERE lower(email)=lower(?) OR phone=? ORDER BY id LIMIT 1').get(email,phone);if(customer)db.prepare('UPDATE customers SET name=?,email=?,phone=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,email,phone,customer.id);else{const result=db.prepare('INSERT INTO customers (name,email,phone) VALUES (?,?,?)').run(name,email,phone);customer={id:result.lastInsertRowid};}const result=db.prepare('INSERT INTO appointments (customer_id,service_id,date,time,end_time,note) VALUES (?,?,?,?,?,?)').run(customer.id,serviceId,date,time,endTime,note);return{id:result.lastInsertRowid,customerId:customer.id};});const appointment=create();try{await sendAppointmentNotifications({appointment,customer:{name,email,phone},service:{name:service.name}});}catch(error){console.error('Appointment email failed:',error);}return res.status(201).json({message:'Termin erfolgreich angefragt.',appointment});}catch(error){if(error.code==='SLOT_TAKEN'||error.code==='SQLITE_CONSTRAINT_UNIQUE')return res.status(409).json({message:'Dieser Zeitraum wurde gerade vergeben. Bitte wähle eine andere Uhrzeit.'});console.error(error);return res.status(500).json({message:'Termin konnte nicht gespeichert werden.'});}});
router.get('/reviews',(_req,res)=>{const reviews=db.prepare("SELECT id,customer_name AS customerName,rating,text,created_at AS createdAt FROM reviews WHERE status='Freigegeben' ORDER BY created_at DESC LIMIT 20").all();res.json({reviews});});
export { STATUSES };
export default router;
